[meta]
version = 1
name = "Omarchy"
description = "Follow your Omarchy system theme."
variant = "dark"
inherits = "vicinae-dark"
icon = "/home/el/.local/share/omarchy/icon.png"

[colors.core]
background = "#F5E6D3"
foreground = "#35302a"
secondary_background = "#faebd8"
border = "#6F4C3E"
accent = "#644535"

[colors.list.item.hover]
background = "#fff0dd"
foreground = "#35302a"

[colors.list.item.selection]
background = "#104f5e2"
foreground = "#35302a"

[colors.accents]
blue = "#AD9980"
green = "#b76e79"
magenta = "#b76e81"
orange = "#644535"
purple = "#b76e81"
red = "#a02b16"
yellow = "#694C45"
cyan = "#3b3b28"
