# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, flatpak run app.zen_browser.zen
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
#
unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive,

unbind = SUPER, SPACE
bindd = SUPER, SPACE, vicinae, exec, uwsm-app -- vicinae toggle

unbind = , PRINT
bindd = , PRINT, hyprshot region, exec, hyprshot -m region
bindd = CTRL, PRINT, hyprshot window, exec, hyprshot -m window
bindd = CTRL ALT, PRINT, hyprshot output, exec, hyprshot -m fullscreen

unbind = ALT, TAB 
unbind = ALT SHIFT, TAB
bindd = ALT, TAB, Next window, exec, uwsm-app -- snappy-switcher next
bindd = ALT SHIFT, TAB, Previous window, exec, uwsm-app -- snappy-switcher prev


